# Generated by Django 4.2.7 on 2024-01-16 09:30

from django.db import migrations, models
import django.db.models.deletion
import jdatetime


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub', models.CharField(max_length=45)),
                ('Summary', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='media/')),
                ('publisher', models.CharField(default='amir', max_length=20)),
                ('description', models.TextField()),
                ('published', models.DateTimeField(default=jdatetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Index',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('description', models.TextField()),
                ('published', models.DateTimeField(default=jdatetime.datetime.now)),
                ('approved', models.BooleanField(default=False)),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myblog.blog')),
            ],
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('published', models.DateTimeField(default=jdatetime.datetime.now)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myblog.person')),
            ],
        ),
    ]
